groups:
- name: Hardware alerts
  rules:
  - alert: Node down
    expr: up{job="node-exporter"} == 0
    for: 10s
    labels:
      severity: warning
    annotations:
      title: Node {{ $labels.instance }} is down
      description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 10 seconds. Node seems down.